In [11]:
import math

In [15]:
a=math.sin(math.pi/6) 
print (a)

0.49999999999999994


In [16]:
b=a*2
print (b)

0.9999999999999999


In [1]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])

In [2]:
a.shape

(4,)

In [3]:
c.shape

(3, 4)

In [6]:
c.shape=4,3
print (c)

[[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  9 10]]


In [7]:
a.dtype

dtype('int32')

In [9]:
c

array([[ 1,  2,  3],
       [ 4,  4,  5],
       [ 6,  7,  7],
       [ 8,  9, 10]])

In [10]:
h=np.logspace(0,1,10)
h

array([ 1.        ,  1.29154967,  1.66810054,  2.15443469,  2.7825594 ,
        3.59381366,  4.64158883,  5.9948425 ,  7.74263683, 10.        ])

In [15]:
import time
x=[i*0.001 for i in range(1000000)]
x=np.array(x)
start=time.perf_counter()
np.sin(x,x)
print("numpy.sin:",time.perf_counter()-start)

numpy.sin: 0.0008253510004578857


In [16]:
x

array([0.        , 0.001     , 0.002     , ..., 0.82518868, 0.82575313,
       0.82631675])

In [29]:
a=range(10)
print(a)

range(0, 10)


In [25]:
y=[i*0.001 for i in range(1000)]

In [30]:
import aa

ModuleNotFoundError: No module named 'aa'

In [31]:
import scipy